// Code generated by `gsxmail import`. Review IMPORT-REPORT.md before you
// ship it: every field below is a best-effort synthesis from the source
// HTML's own literal text, not a guarantee about your real data shape.
package emails

// MagicLinkProps fills the imported template.
type MagicLinkProps struct {
	Lede        string // the headline's own lede paragraph ("Use this code within the next 10 minutes to finish signin...")
	OneTimeCode string // the Panel row labeled "ONE-TIME CODE" ("central: 481 902")
	Expires     string // the Panel row labeled "EXPIRES" ("10 minutes from now")
	Title       string // the document's own <title> ("Sign in to Acme")
	Wordmark    string // the Shell header's own wordmark text ("Sign")
	Preheader   string // the hidden inbox-preview div's own text ("Your one-time code is ready")
}
