// MagicLinkEmail.gsx was generated by `gsxmail import` from react-email.html.
// Review IMPORT-REPORT.md before you ship it: every synthesized props
// field, and every email.Custom fallback block, is listed there with its
// own confidence and source snippet.
package emails

func MagicLinkEmail(props MagicLinkProps) Node {
    return <email.Shell
        wordmark={props.Wordmark}
        shortCode="SIG"
        tagline=""
        title={props.Title}
        lang="en"
        preheader={props.Preheader}>
        <email.Headline title={"Your sign-in code"} lede={props.Lede} />
        <email.Panel>
            <email.PanelRow label={"ONE-TIME CODE"} value={props.OneTimeCode} />
            <email.PanelRow label={"EXPIRES"} value={props.Expires} />
        </email.Panel>
        <email.Button variant="primary" label={"Confirm sign-in"} href={"https://acme.example/verify/481902"} />
        <email.Divider />
        <table style="width:100%;">
        <tr>
        <td><p style={"font-size:12px; line-height:20px; color:#8898aa; margin:0;"}>{"Acme, 1 Market St, San Francisco, CA. If you did not request this code, you can ignore this email."}</p></td>
        </tr>
        </table>
    </email.Shell>
}
