// Code generated by `gsxmail import`. This file is optional: it is the
// only generated file that imports m31labs.dev/gsxmail. Delete it (and
// the gsxmail.Options{Theme: ...} reference at your call site) if you do
// not want the extracted theme, or are generating props.go outside a
// gsxmail module entirely — template.gsx and props.go stand on their own
// without it.
package emails

import "m31labs.dev/gsxmail"

// ImportedTheme reproduces the color palette gsxmail import extracted
// from the source HTML's own literal colors (see IMPORT-REPORT.md's
// "Theme extraction" section for exactly which tokens it read versus
// defaulted). Pass it as gsxmail.Options{Theme: ImportedTheme()}, or
// replace it with gsxmail.DefaultTheme() or your own Theme value.
func ImportedTheme() gsxmail.Theme {
	return gsxmail.Theme{
		ColorGround: "#FFFFFF",
		ColorCard:   "#FFFFFF",
		ColorPanel:  "#F7F7F9",
		ColorBorder: "#E2E2E8",
		ColorAccent: "#5469D4",
		ColorInk:    "#1A1A1A",
		ColorBody:   "#3C3C46",
		ColorMuted:  "#71717F",
		ColorFaint:  "#9C9CA8",
		FontSans:    "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif",
		FontMono:    "'SFMono-Regular',Consolas,Menlo,monospace",
		CardWidth:   600,
	}
}
