// Code generated by `gsxmail import`. Review IMPORT-REPORT.md before you
// ship it: every field below is a best-effort synthesis from the source
// HTML's own literal text, not a guarantee about your real data shape.
package emails

import "m31labs.dev/gsxmail"

// DigestProps fills the imported template.
type DigestProps struct {
	Lede     string // the headline's own lede paragraph ("Five stories worth your Friday afternoon, picked by the e...")
	Title    string // the document's own <title> ("Acme Digest")
	Wordmark string // the Shell header's own wordmark text ("Acme")
}

// ImportedTheme reproduces the color palette gsxmail import extracted
// from the source HTML's own literal colors (see IMPORT-REPORT.md's
// "Theme extraction" section for exactly which tokens it read versus
// defaulted). Pass it as gsxmail.Options{Theme: ImportedTheme()}, or
// replace it with gsxmail.DefaultTheme() or your own Theme value.
func ImportedTheme() gsxmail.Theme {
	return gsxmail.Theme{
		ColorGround: "#F4F4F6",
		ColorCard:   "#FFFFFF",
		ColorPanel:  "#F7F7F9",
		ColorBorder: "#E2E2E8",
		ColorAccent: "#3452FF",
		ColorInk:    "#16161D",
		ColorBody:   "#3C3C46",
		ColorMuted:  "#71717F",
		ColorFaint:  "#9C9CA8",
		FontSans:    "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif",
		FontMono:    "'SFMono-Regular',Consolas,Menlo,monospace",
		CardWidth:   600,
	}
}
