// Code generated by `gsxmail import`. Review IMPORT-REPORT.md before you
// ship it: every field below is a best-effort synthesis from the source
// HTML's own literal text, not a guarantee about your real data shape.
package emails

// DigestProps fills the imported template.
type DigestProps struct {
	Lede     string // the headline's own lede paragraph ("Five stories worth your Friday afternoon, picked by the e...")
	Title    string // the document's own <title> ("Acme Digest")
	Wordmark string // the Shell header's own wordmark text ("Acme")
}
