// DigestEmail.gsx was generated by `gsxmail import` from mjml.html.
// Review IMPORT-REPORT.md before you ship it: every synthesized props
// field, and every email.Custom fallback block, is listed there with its
// own confidence and source snippet.
package emails

func DigestEmail(props DigestProps) Node {
    return <email.Shell
        wordmark={props.Wordmark}
        shortCode="ACM"
        tagline=""
        title={props.Title}
        lang="en"
        preheader="">
        <email.Headline title={"Your weekly Acme digest"} lede={props.Lede} />
        <email.Columns>
            <email.Column title={"Platform: faster builds"} text={"The build pipeline is 40% faster after this week's cache rewrite."} />
            <email.Column title={"Community: office hours"} text={"Join Thursday's open office hours for a live QA with the team."} />
        </email.Columns>
        <email.Button variant="primary" label={"Read the full digest"} href={"https://acme.example/digest/42"} />
        <table style="width:100%;">
        <tr>
        <td align={"center"} style={"font-size:0px; padding:16px 20px 28px 20px;"}><a href={"https://twitter.com/acme"}><img width={"24"} height={"24"} style={"border:0;"} src={"https://example.com/imported-asset.png"} alt={"Twitter"} /></a><a href={"https://github.com/acme"}><img width={"24"} height={"24"} style={"border:0;"} src={"https://example.com/imported-asset.png"} alt={"GitHub"} /></a></td>
        </tr>
        </table>
    </email.Shell>
}
