// Code generated by `gsxmail import`. Review IMPORT-REPORT.md before you
// ship it: every field below is a best-effort synthesis from the source
// HTML's own literal text, not a guarantee about your real data shape.
package emails

// NewsletterProps fills the imported template.
type NewsletterProps struct {
	Lede     string // the headline's own lede paragraph ("Five things from the shop floor this month.")
	Issue    string // the Panel row labeled "ISSUE" ("No. 42")
	Date     string // the Panel row labeled "DATE" ("August 2026")
	Title    string // the document's own <title> ("Acme Newsletter")
	Wordmark string // the Shell header's own wordmark text ("Acme")
}
