// NewsletterEmail.gsx was generated by `gsxmail import` from legacy.html.
// Review IMPORT-REPORT.md before you ship it: every synthesized props
// field, and every email.Custom fallback block, is listed there with its
// own confidence and source snippet.
package emails

func NewsletterEmail(props NewsletterProps) Node {
    return <email.Shell
        wordmark={props.Wordmark}
        shortCode="ACM"
        tagline=""
        title={props.Title}
        lang="en"
        preheader="">
        <email.Headline title={"Acme Weekly"} lede={props.Lede} />
        <email.Panel>
            <email.PanelRow label={"ISSUE"} value={props.Issue} />
            <email.PanelRow label={"DATE"} value={props.Date} />
        </email.Panel>
        <email.Button variant="primary" label={"Read the full issue on the web"} href={"https://acme.example/newsletter/42"} />
        <email.Hero src={"https://example.com/imported-asset.png"} alt={"Acme"} width={"600"} height={"300"} />
        <email.Divider />
        <table style="width:100%;">
        <tr>
        <td align={"center"}><div><span face={"Arial"} size={"1"} color={"#999999"}>{"2026 Acme Corp, 1 Market St, Springfield."}<a href={"https://example.com/imported-link"}>{"Unsubscribe"}</a></span></div></td>
        </tr>
        </table>
    </email.Shell>
}
