package importer

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// propsTypeName derives the declared props struct's own name from
// templateName, matching the shipped gallery's convention exactly
// (receipt.gsx's "ReceiptEmail" / "ReceiptProps", welcome.gsx's
// "WelcomeEmail" / "WelcomeProps"): strip a trailing "Email", append
// "Props".
func propsTypeName(templateName string) string {
	base := strings.TrimSuffix(templateName, "Email")
	if base == "" {
		base = templateName
	}
	return base + "Props"
}

// quoteLit renders s as a plain Go-quoted string literal, for the small
// set of attributes Import always writes as a static literal rather than
// an {expression} hole (email.Shell's own lang and shortCode) — both are
// short, source-controlled values (a 2-3 letter code, a BCP-47-shaped
// language tag), never arbitrary derived text, so a literal reads better
// than a synthesized props field would.
func quoteLit(s string) string {
	return strconv.Quote(s)
}

// assemble builds Result's four outputs from every piece Import.go
// already recovered: the Shell frame, the ordered block list, and the
// props/theme state props accumulated along the way.
func assemble(pkg, templateName, sourceName string, shell shellInfo, blocks []mappedBlock, props *propsBuilder, rpt *Report,
	titleField, wordmarkField, taglineField, preheaderField string) (*Result, error) {
	propsType := propsTypeName(templateName)

	var b strings.Builder
	fmt.Fprintf(&b, "// %s.gsx was generated by `gsxmail import` from %s.\n", templateName, sourceName)
	b.WriteString("// Review IMPORT-REPORT.md before you ship it: every synthesized props\n")
	b.WriteString("// field, and every email.Custom fallback block, is listed there with its\n")
	b.WriteString("// own confidence and source snippet.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "func %s(props %s) Node {\n", templateName, propsType)
	b.WriteString("    return <email.Shell\n")
	fmt.Fprintf(&b, "        wordmark={props.%s}\n", wordmarkField)
	fmt.Fprintf(&b, "        shortCode=%s\n", quoteLit(shell.shortCode))
	if taglineField != "" {
		fmt.Fprintf(&b, "        tagline={props.%s}\n", taglineField)
	} else {
		b.WriteString("        tagline=\"\"\n")
	}
	fmt.Fprintf(&b, "        title={props.%s}\n", titleField)
	fmt.Fprintf(&b, "        lang=%s\n", quoteLit(orDefault(shell.lang, "en")))
	if preheaderField != "" {
		fmt.Fprintf(&b, "        preheader={props.%s}>\n", preheaderField)
	} else {
		b.WriteString("        preheader=\"\">\n")
	}
	for _, blk := range blocks {
		b.WriteString(indent(indent(blk.gsx)))
	}
	b.WriteString("    </email.Shell>\n")
	b.WriteString("}\n")

	for _, f := range props.fields {
		rpt.Fields = append(rpt.Fields, propsFieldReportLine{Name: f.name, GoType: f.goType, Source: f.source})
	}

	propsGo := writePropsGo(pkg, propsType, props, shell.theme, shell.cardWidth)
	sampleJSON, err := writeSampleJSON(props)
	if err != nil {
		return nil, err
	}

	return &Result{
		TemplateName:    templateName,
		TemplateGSX:     b.String(),
		PropsGo:         propsGo,
		SamplePropsJSON: sampleJSON,
		Report:          rpt,
		blocks:          blocks,
	}, nil
}

// writePropsGo renders props.go: one synthesized row struct per
// props.rowTypes (StatTable's own Each-driven "ItemsRow{ Cells []string
// }" shape), then the declared props struct itself, each field carrying
// a comment naming the source text it came from — the report's own
// per-field detail, restated at the point of use so a reader tuning the
// struct never has to cross-reference IMPORT-REPORT.md for the common
// case.
func writePropsGo(pkg, propsType string, props *propsBuilder, theme themeTokens, cardWidth int) string {
	var b strings.Builder
	b.WriteString("// Code generated by `gsxmail import`. Review IMPORT-REPORT.md before you\n")
	b.WriteString("// ship it: every field below is a best-effort synthesis from the source\n")
	b.WriteString("// HTML's own literal text, not a guarantee about your real data shape.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import \"m31labs.dev/gsxmail\"\n\n")

	for _, rt := range props.rowTypes {
		fmt.Fprintf(&b, "// %s is one synthesized row (see IMPORT-REPORT.md for its source table).\n", rt.name)
		fmt.Fprintf(&b, "type %s struct {\n", rt.name)
		for _, f := range rt.fields {
			fmt.Fprintf(&b, "\t%s []string\n", f)
		}
		b.WriteString("}\n\n")
	}

	fmt.Fprintf(&b, "// %s fills the imported template.\n", propsType)
	fmt.Fprintf(&b, "type %s struct {\n", propsType)
	for _, f := range props.fields {
		fmt.Fprintf(&b, "\t%s %s // %s\n", f.name, f.goType, commentSource(f))
	}
	b.WriteString("}\n\n")

	b.WriteString("// ImportedTheme reproduces the color palette gsxmail import extracted\n")
	b.WriteString("// from the source HTML's own literal colors (see IMPORT-REPORT.md's\n")
	b.WriteString("// \"Theme extraction\" section for exactly which tokens it read versus\n")
	b.WriteString("// defaulted). Pass it as gsxmail.Options{Theme: ImportedTheme()}, or\n")
	b.WriteString("// replace it with gsxmail.DefaultTheme() or your own Theme value.\n")
	b.WriteString("func ImportedTheme() gsxmail.Theme {\n")
	b.WriteString("\treturn gsxmail.Theme{\n")
	fmt.Fprintf(&b, "\t\tColorGround: %s,\n", quoteLit(theme.ColorGround))
	fmt.Fprintf(&b, "\t\tColorCard:   %s,\n", quoteLit(theme.ColorCard))
	fmt.Fprintf(&b, "\t\tColorPanel:  %s,\n", quoteLit(theme.ColorPanel))
	fmt.Fprintf(&b, "\t\tColorBorder: %s,\n", quoteLit(theme.ColorBorder))
	fmt.Fprintf(&b, "\t\tColorAccent: %s,\n", quoteLit(theme.ColorAccent))
	fmt.Fprintf(&b, "\t\tColorInk:    %s,\n", quoteLit(theme.ColorInk))
	fmt.Fprintf(&b, "\t\tColorBody:   %s,\n", quoteLit(theme.ColorBody))
	fmt.Fprintf(&b, "\t\tColorMuted:  %s,\n", quoteLit(theme.ColorMuted))
	fmt.Fprintf(&b, "\t\tColorFaint:  %s,\n", quoteLit(theme.ColorFaint))
	fmt.Fprintf(&b, "\t\tFontSans: %s,\n", quoteLit(theme.FontSans))
	fmt.Fprintf(&b, "\t\tFontMono: %s,\n", quoteLit(theme.FontMono))
	fmt.Fprintf(&b, "\t\tCardWidth: %d,\n", cardWidth)
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// commentSource renders one props field's source as a short trailing Go
// comment: the source description, plus (for a plain string field) the
// harvested literal itself, truncated so a long paragraph does not
// produce an unreadable comment line.
func commentSource(f propsField) string {
	switch v := f.sample.(type) {
	case string:
		return f.source + " (" + truncateForComment(v) + ")"
	default:
		return f.source
	}
}

func truncateForComment(s string) string {
	r := []rune(s)
	if len(r) <= 60 {
		return strconv.Quote(s)
	}
	return strconv.Quote(string(r[:57]) + "...")
}

// writeSampleJSON renders props.sample.json: one JSON object keyed by
// every field's own Go name, with the harvested sample values Import
// collected along the way (task instructions, item 3: "props.sample.json
// (values harvested from the source text)").
func writeSampleJSON(props *propsBuilder) (string, error) {
	obj := make(map[string]any, len(props.fields))
	for _, f := range props.fields {
		obj[f.name] = f.sample
	}
	data, err := json.MarshalIndent(obj, "", "  ")
	if err != nil {
		return "", fmt.Errorf("importer: encoding props.sample.json: %w", err)
	}
	return string(data) + "\n", nil
}
